trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'iotdevicewebapi'
  containerRegistry: 'myregistry.azurecr.io'
  dockerfilePath: 'Dockerfile'
  buildContext: '.'
  environment: 'prod'  # Change to 'staging' or 'prod' as needed

steps:
- task: DockerInstaller@0
  displayName: 'Install Docker'

- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: 'build'
    dockerfile: '$(dockerfilePath)'
    buildContext: '$(buildContext)'
    tags: |
      $(containerRegistry)/$(imageName):$(Build.BuildId)
      $(containerRegistry)/$(imageName):$(environment)

- task: Docker@2
  displayName: 'Push Docker Image to ACR'
  inputs:
    command: 'push'
    tags: |
      $(containerRegistry)/$(imageName):$(Build.BuildId)
      $(containerRegistry)/$(imageName):$(environment)

- task: AzureCLI@2
  displayName: 'Deploy to Azure Container Instance'
  inputs:
    azureSubscription: 'AzureRM-LAB_ADtoGithub'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az container create \
        --resource-group myResourceGroup \
        --name iotdevicewebapi-$(environment) \
        --image $(containerRegistry)/$(imageName):$(environment) \
        --cpu 1 --memory 1.5 \
        --registry-login-server $(containerRegistry) \
        --registry-username $(ACR_USERNAME) \
        --registry-password $(ACR_PASSWORD) \
        --dns-name-label iotdevicewebapi-$(environment)-$(Build.BuildId) \
        --ports 80
    env:
      ACR_USERNAME: $(acrUsername)
      ACR_PASSWORD: $(acrPassword)
