apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotdevicewebapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotdevicewebapi
  template:
    metadata:
      labels:
        app: iotdevicewebapi
    spec:
      containers:
      - name: iotdevicewebapi
        image: acriotdevicewebapp.azurecr.io/iotdevicewebapi:latest
        ports:
        - containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata:
  name: iotdevicewebapi-service
spec:
  type: LoadBalancer
  selector:
    app: iotdevicewebapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      
